const VERTICE={whatsapp:"5519971315434",email:"biogasvertice@gmail.com"};
const qs=(s,c=document)=>c.querySelector(s);const qsa=(s,c=document)=>[...c.querySelectorAll(s)];
function track(name,params={}){if(typeof window.gtag==="function")window.gtag("event",name,params)}
function campaignData(){const p=new URLSearchParams(location.search);const keys=["utm_source","utm_medium","utm_campaign","utm_term","utm_content","gclid"];const out={};keys.forEach(k=>{const value=p.get(k)||sessionStorage.getItem(`vertice_${k}`);if(value){out[k]=value;sessionStorage.setItem(`vertice_${k}`,value)}});return out}
function whatsappLink(message){return `https://wa.me/${VERTICE.whatsapp}?text=${encodeURIComponent(message)}`}
function genericMessage(origin){return `Olá! Vim ${origin?`da página ${origin}`:"do site da Vértice"} e quero entender se um projeto de biogás ou biodigestor faz sentido para minha operação.`}
const menuBtn=qs(".menu-btn"),navLinks=qs(".nav-links");if(menuBtn&&navLinks){menuBtn.addEventListener("click",()=>{const open=navLinks.classList.toggle("open");menuBtn.setAttribute("aria-expanded",String(open))});qsa("a",navLinks).forEach(a=>a.addEventListener("click",()=>navLinks.classList.remove("open")))}
const storedCampaign=campaignData();const campaignQuery=new URLSearchParams(storedCampaign).toString();if(campaignQuery){qsa('a[href="/#contato"]').forEach(a=>a.href=`/?${campaignQuery}#contato`)}
qsa("[data-whatsapp]").forEach(link=>{const origin=link.dataset.whatsapp||document.body.dataset.page||"site";link.href=whatsappLink(genericMessage(origin));link.target="_blank";link.rel="noopener";link.addEventListener("click",()=>track("whatsapp_click",{page_location:location.href,contact_origin:origin}))});
const form=qs("#lead-form");if(form){const callTime=qs("#call-time"),callWrap=qs("#call-time-wrap");const refreshCall=()=>{const phone=qs('input[name="contact_method"]:checked',form)?.value==="ligacao";callWrap.hidden=!phone;callTime.required=phone};qsa('input[name="contact_method"]',form).forEach(r=>r.addEventListener("change",refreshCall));refreshCall();form.addEventListener("submit",e=>{e.preventDefault();if(!form.reportValidity()||form.website.value)return;const d=new FormData(form);const method=d.get("contact_method");const camp=campaignData();const source=Object.entries(camp).map(([k,v])=>`${k}: ${v}`).join(" | ")||"acesso direto/orgânico";const message=`Olá! Vim do site da Vértice e quero falar com a consultoria sobre um projeto de biogás/biodigestor.\n\nNome: ${d.get("name")}\nTelefone: ${d.get("phone")}\nCidade/UF: ${d.get("location")}\nOperação: ${d.get("operation")}\nResíduo: ${d.get("waste")||"a informar"}\nVolume aproximado: ${d.get("volume")||"a informar"}\nPrincipal objetivo: ${d.get("goal")||"a informar"}\nMomento da decisão: ${d.get("stage")}\nPreferência: ${method==="ligacao"?`receber ligação — melhor horário: ${d.get("call_time")}`:"continuar pelo WhatsApp"}\nObservação: ${d.get("details")||"sem observação"}\nOrigem: ${source}`;track("generate_lead",{method,lead_goal:d.get("goal"),lead_stage:d.get("stage"),operation_type:d.get("operation"),page_location:location.href});window.open(whatsappLink(message),"_blank","noopener");qs("#form-content").hidden=true;qs("#form-success").classList.add("show")})}
qsa("details").forEach(d=>d.addEventListener("toggle",()=>{if(d.open)track("faq_open",{faq_question:qs("summary",d)?.textContent||""})}));
document.querySelectorAll("[data-year]").forEach(el=>el.textContent=new Date().getFullYear());
